# Generated by Django 3.2 on 2024-09-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionrequest',
            name='notification',
            field=models.CharField(max_length=40),
        ),
    ]
