# Generated by Django 3.2 on 2024-09-24 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=900)),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='post_images/')),
                ('likes', models.CharField(default='', max_length=900)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile_img', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user_profile.userprofile')),
            ],
        ),
    ]
