# Generated by Django 3.2 on 2024-09-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='likes',
            field=models.CharField(default='', max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='message',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
